export const productsDb = [
  {
    name: "Sony PlayStation 5",
    color: "White",
    category: "Console",
    price: "$499",
    available: true,
  },
  {
    name: "Xbox Series X",
    color: "Black",
    category: "Console",
    price: "$499",
    available: true,
  },
  {
    name: "Nintendo Switch OLED",
    color: "White",
    category: "Console",
    price: "$349",
    available: true,
  },
  {
    name: "Razer DeathAdder V2",
    color: "Black",
    category: "Mouse",
    price: "$69",
    available: true,
  },
  {
    name: "Logitech MX Master 3",
    color: "Graphite",
    category: "Mouse",
    price: "$99",
    available: true,
  },
  {
    name: "Samsung 32” Odyssey G7",
    color: "Black",
    category: "Monitor",
    price: "$799",
    available: true,
  },
  {
    name: "LG 27” 4K UHD Monitor",
    color: "Black",
    category: "Monitor",
    price: "$499",
    available: true,
  },
  {
    name: "Acer Predator Helios 300",
    color: "Black",
    category: "Laptop",
    price: "$1599",
    available: true,
  },
  {
    name: "HP Spectre x360",
    color: "Nightfall Black",
    category: "Laptop",
    price: "$1499",
    available: true,
  },
  {
    name: "Google Pixel 6",
    color: "Stormy Black",
    category: "Smartphone",
    price: "$599",
    available: true,
  },
  {
    name: "Apple AirPods Pro 2",
    color: "White",
    category: "Accessories",
    price: "$249",
    available: true,
  },
  {
    name: "JBL Flip 5",
    color: "Blue",
    category: "Speaker",
    price: "$119",
    available: true,
  },
  {
    name: "Sonos One SL",
    color: "Black",
    category: "Speaker",
    price: "$199",
    available: true,
  },
  {
    name: "Samsung Galaxy Tab S8",
    color: "Graphite",
    category: "Tablet",
    price: "$699",
    available: true,
  },
  {
    name: "Kindle Paperwhite",
    color: "Black",
    category: "E-Reader",
    price: "$139",
    available: true,
  },
  {
    name: "Amazon Echo Dot 4th Gen",
    color: "Charcoal",
    category: "Smart Speaker",
    price: "$49",
    available: true,
  },
  {
    name: "Apple HomePod Mini",
    color: "Space Gray",
    category: "Smart Speaker",
    price: "$99",
    available: true,
  },
  {
    name: "Nest Learning Thermostat",
    color: "White",
    category: "Smart Home",
    price: "$129",
    available: true,
  },
  {
    name: "Wyze Cam v3",
    color: "White",
    category: "Smart Home",
    price: "$35",
    available: true,
  },
  {
    name: "Sony A7 III",
    color: "Black",
    category: "Camera",
    price: "$1999",
    available: true,
  },
  {
    name: "Apple AirPods 3rd Gen",
    color: "White",
    category: "Accessories",
    price: "$179",
    available: true,
  },
  {
    name: "Shure SM7B",
    color: "Black",
    category: "Microphone",
    price: "$399",
    available: true,
  },
  {
    name: "Blue Yeti X",
    color: "Black",
    category: "Microphone",
    price: "$169",
    available: true,
  },
  {
    name: "Fitbit Charge 5",
    color: "Black",
    category: "Fitness Tracker",
    price: "$149",
    available: true,
  },
  {
    name: "Withings Steel HR",
    color: "Black",
    category: "Smartwatch",
    price: "$199",
    available: true,
  },
  {
    name: "Apple Mac Mini",
    color: "Space Gray",
    category: "Desktop",
    price: "$699",
    available: true,
  },
  {
    name: "Dell Inspiron Desktop",
    color: "Black",
    category: "Desktop",
    price: "$599",
    available: true,
  },
  {
    name: "HP Omen 30L",
    color: "Black",
    category: "Desktop",
    price: "$1699",
    available: true,
  },
  {
    name: "Apple Magic Keyboard",
    color: "White",
    category: "Accessories",
    price: "$99",
    available: true,
  },
  {
    name: "Logitech G915 TKL",
    color: "Black",
    category: "Keyboard",
    price: "$229",
    available: true,
  },
  {
    name: "Razer Kraken V3",
    color: "Black",
    category: "Headset",
    price: "$129",
    available: true,
  },
  {
    name: "Logitech G Pro X",
    color: "Blue",
    category: "Headset",
    price: "$199",
    available: true,
  },
  {
    name: "Wacom Cintiq Pro 16",
    color: "Black",
    category: "Graphics Tablet",
    price: "$1499",
    available: true,
  },
  {
    name: "Microsoft Surface Book 3",
    color: "Platinum",
    category: "Laptop",
    price: "$1599",
    available: true,
  },
  {
    name: "Asus ROG Strix G15",
    color: "Black",
    category: "Laptop",
    price: "$1399",
    available: true,
  },
  {
    name: "Samsung Galaxy Buds Pro",
    color: "Phantom Violet",
    category: "Accessories",
    price: "$199",
    available: true,
  },
  {
    name: "Sony Xperia 1 IV",
    color: "Black",
    category: "Smartphone",
    price: "$1399",
    available: true,
  },
  {
    name: "Apple TV 4K",
    color: "Black",
    category: "Streaming Device",
    price: "$179",
    available: true,
  },
  {
    name: "Nvidia GeForce RTX 3080",
    color: "Black",
    category: "Graphics Card",
    price: "$699",
    available: true,
  },
  {
    name: 'Apple MacBook Pro 17"',
    color: "Silver",
    category: "Laptop",
    price: "$2999",
    available: true,
  },
  {
    name: "Microsoft Surface Pro",
    color: "White",
    category: "Laptop PC",
    price: "$1999",
    available: true,
  },
  {
    name: "Magic Mouse 2",
    color: "Black",
    category: "Accessories",
    price: "$99",
    available: true,
  },
  {
    name: "Apple iPhone 15",
    color: "Blue",
    category: "Smartphone",
    price: "$999",
    available: true,
  },
  {
    name: "Samsung Galaxy S23",
    color: "Green",
    category: "Smartphone",
    price: "$899",
    available: true,
  },
  {
    name: "Sony WH-1000XM5",
    color: "Black",
    category: "Headphones",
    price: "$349",
    available: true,
  },
  {
    name: "Bose QuietComfort 45",
    color: "Silver",
    category: "Headphones",
    price: "$329",
    available: true,
  },
  {
    name: "Dell XPS 13",
    color: "Platinum",
    category: "Laptop",
    price: "$1299",
    available: true,
  },
  {
    name: "Lenovo ThinkPad X1 Carbon",
    color: "Black",
    category: "Laptop",
    price: "$1599",
    available: true,
  },
  {
    name: "Apple iPad Pro 12.9",
    color: "Space Gray",
    category: "Tablet",
    price: "$1099",
    available: true,
  },
  {
    name: "Microsoft Surface Go 3",
    color: "Platinum",
    category: "Tablet",
    price: "$499",
    available: true,
  },
];
